#!/usr/bin/env bash
#
# Print system information
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -euo pipefail


# ====== Print banner =======================================================

# Using 24-bit color codes. This may not work with all terminals!
reset="\x1b[0m"
color1="\x1b[38;2;241;71;29m"   # SimulaMet orange: F1471D
color2="\x1b[38;2;33;27;87m"    # SimulaMet dark blue: #211B57

# ------ Print top separator ------------------------------------------------
echo -en "${color1}"
print-utf8 -s "╭🇳🇴" "─" "🇳🇴╮"

# ------ Print the logo -----------------------------------------------------
(
  echo -e "${color1}-- ${color2}$(gettext "Welcome to") ${color1}--"
  figlet -f big "Simula"
  echo -e "🎂 ${color2}25th Anniversary — 2001–2026${color1} 🎂"
) | print-utf8 -C "│" "│"

# ------ Print bottom separator ---------------------------------------------
print-utf8 -s "╰🇳🇴" "─" "🇳🇴╯"
echo -e "${reset}"


# ====== Finish =============================================================

# With exit code 1, no further files in /etc/system-info.d are processed.
# Use exit code 0 to continue processing files.
exit 1   # 1 => Exit processing!
