#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ====== Print script name, to make Packer output easier readable ===========
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ====== Check/set environment variables ====================================
UNAME="$(uname)"


# ====== Configure System-Info ==============================================
if [ "${UNAME}" == "FreeBSD" ] ; then
   systemInfoDirectory="/usr/local/etc/system-info.d"
else
   systemInfoDirectory="/etc/system-info.d"
fi

if [ -d /tmp/system-info ] ; then
   mkdir -p "${systemInfoDirectory}"
   find /tmp/system-info -type f -exec chmod +x {} \;
   find /tmp/system-info -type f -exec cp {} "${systemInfoDirectory}/" \;
else
   echo >&2 "ERROR: /tmp/system-info does not exist!"
   exit 1
fi
