#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ====== Print script name, to make Packer output easier readable ===========
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[22m" "\e[1;32m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"
UNAME="$(uname)"


# ====== Prepare configuration file =========================================
if [ ! -e "${USER_HOME}/.config/strawberry/strawberry.conf" ] ; then
   sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/.config/strawberry"
   ( cat <<EOF
[MainWindow]
do_not_show_sponsor_message=true
EOF
   ) | sudo -u "${USER_NAME}" tee "${USER_HOME}/.config/strawberry/strawberry.conf"
fi

# ====== Add a playlist for Strawberry ======================================
if [ -e /tmp/data-files/Radios.m3u ] ; then
   sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/Music"
   sudo -u "${USER_NAME}" cp /tmp/data-files/Radios.m3u "${USER_HOME}/Music"
fi
if [ -e "${USER_HOME}/Music/Radios.m3u" ] ; then
   sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/Desktop"
   if [ ! -e "${USER_HOME}/Desktop/Radios.m3u" ] ; then
      sudo -u "${USER_NAME}" ln -s "${USER_HOME}/Music/Radios.m3u" "${USER_HOME}/Desktop/"
   fi
fi
