#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Ensure that script is executed by the user account #################
if [ "$(id -u)" -eq 0 ] ; then
   # Running as root using sudo. Run the script again, but as user!
   echo "Running as ROOT! SUDO_USER=${SUDO_USER}"
   if [ "${SUDO_USER}" != "root" ] ; then
      # shellcheck disable=SC2068
      sudo -u "${SUDO_USER}" "$0" $@ && exit 0
      exit 1
   else
      # Prevent recursive invocation as "root" user:
      echo >&2 "ERROR: Run this script either as user or with sudo."
      exit 1
   fi
else
   # Echo running as user
   echo "Running as ${USER}! SUDO_USER=${SUDO_USER:-}"
fi


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Clone or update Git repository #####################################
clone-or-update ()
{
   local repository="$1"
   local url="$2"
   local clone_maxtrials=10
   local clone_delay=60
   if [ ! -e "${repository}" ] ; then
      try-hard ${clone_maxtrials} ${clone_delay} -- git clone "${url}" "${repository}"
   else
      pushd "${repository}" >/dev/null
      try-hard ${clone_maxtrials} ${clone_delay} -- git fetch --all
      try-hard ${clone_maxtrials} ${clone_delay} -- git pull
      popd >/dev/null
   fi
}


# ###### Main program #######################################################

# ====== Check environment variables ========================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release is not available!"
   exit 1
fi
. /etc/os-release
UNAME="$(uname)"


# ====== Prepare directories ================================================
mkdir -p "${HOME}/Desktop"
mkdir -p "${HOME}/src"
mkdir -p "${HOME}/python-environments"
cd "${HOME}/src"

# ====== DeepFakeECG Generator Plus =========================================
if [ "${UNAME}" == "Linux" ] ; then

   # ------ Clone the repository -----------------------------------------------
   clone-or-update deepfake-ecg-generator-plus   https://hf.co/spaces/dreibh/deepfake-ecg-generator-plus

   # Enter the directory of the repository:
   pushd deepfake-ecg-generator-plus >/dev/null


   # ------ Add additional remotes ---------------------------------------------
   if ! git remote get-url search-ihi >/dev/null 2>&1 ; then
      git remote add search-ihi http://hf.co/spaces/SEARCH-IHI/deepfake-ecg-generator-plus
   fi
   if ! git remote get-url deepsynthbody >/dev/null 2>&1 ; then
      git remote add deepsynthbody http://hf.co/spaces/deepsynthbody/deepfake-ecg-generator-plus
   fi
   git fetch --all

   # ------ Prepare and activate Python environment ----------------------------
   python3 -m venv "${HOME}/python-environments/deepfakeecg"
   # shellcheck disable=SC1091
   . "${HOME}/python-environments/deepfakeecg/bin/activate"

   # ------ Install the Python dependencies into the Python environment --------

   # NOTE: The dependencies are relatively large, too big to build them
   #       in /tmp in many cases. A temporary directory is necessary!

   tempDirectory=""
   trap 'rm -rf "${tempDirectory}"' EXIT INT TERM HUP
   tempDirectory="$(mktemp -d pip.XXXXXXXXXXXXXXXX)"
   TMPDIR=${tempDirectory} \
      pip install -r requirements.txt
   rm -rf "${tempDirectory}"


   # ------ Generate a small launcher script -----------------------------------

   # NOTE: The launcher script must contain the paths to the Python environment
   #       and the program => $(pwd) provides the current directory.

   cat >"${HOME}/DeepFakeECG-Launcher" <<EOF
#!/bin/sh -eu

# Activate the Python environment:
. ${HOME}/python-environments/deepfakeecg/bin/activate

# Run the actual launcher script for DeepFakeECG Generator Plus:
cd $(pwd)
./deepfakeecg-launcher
EOF
   chmod +x "${HOME}/DeepFakeECG-Launcher"

   # ------ Generate a desktop icon --------------------------------------------
   # NOTE: The desktop icon must contain the full path to the program.
   #       => $(pwd) provides the current directory.

   cat >"${HOME}/Desktop/DeepFakeECG.desktop" <<EOF
[Desktop Entry]
Comment=Launches DeekFakeECG Generator Plus
Exec=${HOME}/DeepFakeECG-Launcher
Icon=face-smile
Name=DeekFakeECG Generator Plus
StartupNotify=true
Terminal=true
TerminalOptions=
Type=Application
EOF


   # Go back to the original directory:
   popd >/dev/null

else

   # FIXME! # Unfortunately, the dependencies of DeepFakeECG (PyTorch, etc.) are
   # only working under Linux, yet.
   echo >&2 "Unsupported operating system."

fi
