#!/usr/bin/env bash

set -euo pipefail

useradd nornetpp || true
mkdir -p /home/nornetpp
chown nornetpp:nornetpp /home/nornetpp

export USER_NAME="nornetpp"
export USER_REALNAME="NorNet Praesum Presum"
export VIDEO=1920x1080
export BOOTSPLASH=

echo "OK"


./01-system-settings
./05-user-settings
./06-sudo-without-password
./10-basic
./11-system-info
./12-configure-grub
# ./15-zabbix-agent

./20-kde
# ./21-configure-firefox
./22-configure-wireshark
./23-configure-strawberry


LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▀" "█\e[0m" ;
echo "ALL TESTS SUCCEEDED!" | figlet -w 156 | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[25m" "█\e[0m" ;
LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
